#!/bin/bash
    clear
}
#installbotsms
function installbotsms () {
   clear
   wget $HOME -O botsmslocked.zip https://www.dropbox.com/s/ehvxazfpqwakmua/botsmslocked.zip?dl=0
   sleep 3
   botsms
}
#installbotsms2
function installbotsms2 () {
   clear
   apt install zip && unzip botsms.zip && apt install screen && apt install redis && apt install sqlite3 && apt install php-redis && apt install php-curl && apt install php-sqlite3 && cd botsms && sh iniciar.sh && echo -e "\033[1;31mTUDO OK ✅"
   sleep 3
   botsms
}
    figlet "BOT SMS" | lolcat
    echo -e ""
    echo -e "\033[1;37mDEPOIS DE INSTALAR ACESSE OS ARQUIVOS DO BOT NA VPS E"
    echo -e "\033[1;37mCOLOQUE SEU DADOS TOKEN DO TG, TOKEN DO MP, E TOKEN DO SMS NO ARQUIVO DADOS DO BOT NA PASTA INCLUDES"
    echo -e ""
    echo -e "\033[1;37m SITE DE SMS 👉 https://sms-activate.org/"
    echo -e ""
    echo -e "\033[1;37m 01 ➡️\033[1;36m INSTALAR 🤖\033[0m"
	echo -e "\033[1;37m 02 ➡️\033[1;36m FINALIZAR E INÍCIAR BOT 🤖\033[0m"
    echo -e "\033[1;37m 00 ➡️\033[1;31m SAIR \033[0m"
    echo -e "\033[01;31m\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			installbotsms
			;;
			2 | 02)
            installbotsms2
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			esac
			sleep 2
