#!/bin/bash
    clear
    figlet "FERRAMENTAS" | lolcat
    echo -e ""
    echo -e "\033[1;37m 01 ➡️\033[1;36m CONSUMO DA VPS 🖥️\033[0m"
	echo -e "\033[1;37m 02 ➡️\033[1;36m TRAFEGO 📊\033[0m"
	echo -e "\033[1;37m 03 ➡️\033[1;36m OTIMIZAR VPS ♻️\033[0m"
	echo -e "\033[1;37m 04 ➡️\033[1;36m BANNER 🖼️\033[0m"
	echo -e "\033[1;37m 05 ➡️\033[1;36m FIREWALL 🚏\033[0m"
	echo -e "\033[1;37m 06 ➡️\033[1;36m MEMÓRIA SWAP 💾\033[0m"
	echo -e "\033[1;37m 07 ➡️\033[1;36m AUTERAR SENHA ROOT 🔑\033[0m"
	echo -e "\033[1;37m 08 ➡️\033[1;36m BLOQUEAR TORRENT ❌\033[0m"
	echo -e "\033[1;37m 09 ➡️\033[1;36m TCP-TWEAKER 🚀\033[0m"
	echo -e "\033[1;37m 10 ➡️\033[1;36m REINICIAR SISTEMA 🔃\033[0m"
	echo -e "\033[1;37m 11 ➡️\033[1;36m REINICIAR SERVIÇOS 🔃\033[0m"
	echo -e "\033[1;37m 12 ➡️\033[1;36m SPEEDTEST 🚀\033[0m"
    echo -e "\033[1;37m 00 ➡️\033[1;31m SAIR \033[0m"
    echo -e "\033[01;31m\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			painelg
			;;
			2 | 02)
            clear
            echo -e "\033[1;32mPARA SAIR CLICK CTRL + C\033[1;36m"
            sleep 4
            nload
            ;;
            3 | 03)
            clear
            otimizar
            echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
            ;;
            4 | 04)
            clear
            banner
            sleep 3
            ;;
            5 | 05)
            fport
            ;;
            6 | 06)
            swapmemory
            ;;
            7 | 07)
            clear
            senharoot
            sleep 3
            ;;
            8 | 08)
            clear
            blockt
            ;;
            9 | 09)
            clear
            tcptweaker.sh
            ;;
            10 | 10)
            clear
            reiniciarsistema
            sleep 3s
            ;;
            11 | 11)
            clear
            reiniciarservicos
            sleep 3s
            ;;
            12 | 12)
            speedtest
            ;;
            13 | 13)
            autoexec
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			esac
			sleep 2
}
##
function autoexec () {
   if grep "menu;" /etc/profile > /dev/null; then
      clear
      echo -e "\033[1;32mDESATIVANDO AUTO EXECUÇÃO\033[0m"
      offautmenu () {
         sed -i '/menu;/d' /etc/profile
      }
      echo ""
      fun_bar 'offautmenu'
      echo ""
      echo -e "\033[1;31mAUTO EXECUÇÃO DESATIVADO!\033[0m"
      sleep 1.5s
      menu2
   else
      clear
      echo -e "\033[1;32mATIVANDO AUTO EXECUÇÃO\033[0m"
      autmenu () {
         grep -v "^menu;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
         echo "menu;" >> /etc/profile
      }
      echo ""
      fun_bar 'autmenu'
      echo ""
      echo -e "\033[1;32mAUTO EXECUÇÃO ATIVADO!\033[0m"
      sleep 1.5s
      menu2
   fi

}