#!/bin/bash
clear
echo -e "\033[1;37mINSTALANDO FIREWALL E ABRINDO PORTAS AZURE/AWS/ORACLE\033[0m"
sleep 5s
sudo apt-get update && sudo apt install firewalld && sudo firewall-cmd --zone=public --permanent --add-port=80/tcp && sudo firewall-cmd --zone=public --permanent --add-port=443/tcp && sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp && sudo firewall-cmd --zone=public --permanent --add-port=7300/udp && sudo firewall-cmd --zone=public --permanent --add-port=5454/tcp && sudo firewall-cmd --zone=public --permanent --add-port=8181/tcp && sudo firewall-cmd --zone=public --permanent --add-port=5000/tcp && sudo firewall-cmd --reload && sudo firewall-cmd --zone=public --list-ports && 
clear &&
echo -e "\033[1;32mSUSSESO\033[0m" &&
echo -e "\033[1;37mPORTAS 80, 443, 8080, 8181, 5000, 5454, 7300 ABERTAS \033[0m"
sleep 5s
