#!/bin/bash
clear
sleep 1s

figlet "APLICATIVOS" | lolcat

echo -e "\033[1;37mPARA BAIXAR COPIE E COLE ONLINK NO NAVEGADOR \033[0m"


https://www.mediafire.com/file/1z4ahpu2o9zctn1/APLICATIVOS.zip/file