#!/bin/bash
    clear
    figlet "MENU USUÁRIO" | lolcat
    echo -e ""
    echo -e "\033[1;37m 01 ➡️\033[1;36m CRIAR USUÁRIO 🐣\033[0m"
	echo -e "\033[1;37m 02 ➡️\033[1;36m CRIAR USUÁRIO TESTE ⏳\033[0m"
	echo -e "\033[1;37m 03 ➡️\033[1;36m REMOVER USUÁRIO 💀\033[0m"
	echo -e "\033[1;37m 04 ➡️\033[1;36m AUTERAR DATA DO USUÁRIO 📅\033[0m"
	echo -e "\033[1;37m 05 ➡️\033[1;36m AUTERAR LIMITE DO USUÁRIO 📵\033[0m"
	echo -e "\033[1;37m 06 ➡️\033[1;36m AUTERAR SENHA DO USUÁRIO 🔑\033[0m"
	echo -e "\033[1;37m 07 ➡️\033[1;36m REMOVER USUÁRIOS EXPIRADS 🛑\033[0m"
	echo -e "\033[1;37m 08 ➡️\033[1;36m LISTA DE USUÁRIOS 📋\033[0m"
	echo -e "\033[1;37m 09 ➡️\033[1;36m VISUALIZAR USUÁRIOS ON-LINE 🟢 \033[0m"
    echo -e "\033[1;37m 00 ➡️\033[1;31m SAIR \033[0m"
    echo -e "\033[01;31m\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			clear
            criarusuario
            echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
			;;
			2 | 02)
            clear
            criarteste
            echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
            ;;
            3 | 03)
            clear
            remover
            sleep 3
            ;;
            4 | 04)
            clear
            mudardata
            sleep 3
            ;;
            5 | 05)
            clear
            alterarlimite
            sleep 3
            ;;
            6 | 06)
            clear
            alterarsenha
            sleep 3
            ;;
            7 | 07)
            clear
            expcleaner
            echo ""
            sleep 3
            ;;
            8 | 08)
            clear
            infousers
            echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
            ;;     
            9 | 09)
            clear
            sshmonitor
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			esac
			sleep 2
