#!/bin/bash
    clear
    figlet "BOTS" | lolcat
    echo -e ""
    echo -e "\033[1;37m 01 ➡️\033[1;36m BOT BACKUP & VENDAS 🤖\033[0m"
	echo -e "\033[1;37m 02 ➡️\033[1;36m BOT TESTE 🤖\033[0m"
	echo -e "\033[1;37m 03 ➡️\033[1;36m BOT WHATSAPP & TELEGRAM 💰\033[0m"
	echo -e "\033[1;37m 04 ➡️\033[1;36m BOT SMS 📨\033[0m"
    echo -e "\033[1;37m 00 ➡️\033[1;31m SAIR \033[0m"
    echo -e "\033[01;31m\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			botssh
			;;
			2 | 02)
            inst-botteste
            ;;
            3 | 03)
            terminus
            ;;
            4 | 04)
            botsms
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			esac
			sleep 2
